### PR TITLE
Use short-enums for bindings

### PR DESCRIPTION
**Pull request by boozook**
Following PR #35.

### CODE REVIEW

**Comment by boozook** [comment]
Okay, prebuilt bindings have to be re-generated. 🤦‍♂️

**Comment by boozook** [comment]
Seems to clang ignoring `-fshort-enums` 🤷‍♂️

**Comment by boozook** [comment]
CC @Psychotropos

**Comment by Psychotropos** [comment]
I think this is related to the changes in furi.rs as part of this PR - the type of FuriStatus should be treated by the compiler as an i32 (which is as expected, as per https://github.com/flipperdevices/flipperzero-firmware/blob/ec57dd310a6ad9657c08d143bd82a66da532dc78/furi/core/base.h#L38)

**Comment by boozook** [comment]
Good point, thanks!

**Pull request merged**
